services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shy_app
    environment:
      - SYMFONY_ENV=dev
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    networks:
      - app-network
    depends_on:
      - database

  database:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: supersaiyan
      MYSQL_DATABASE: db_shy
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"  # Exposer MySQL pour des connexions externes si nécessaire

networks:
  app-network:
    driver: bridge

volumes:
  db_data: