services:
  web:
    build:
      context: .  # Le contexte de construction est le répertoire actuel
      dockerfile: Dockerfile  # Assurez-vous que le fichier s'appelle Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html

    depends_on:
      - database
    networks:
      - app-network

  database:
    image: mysql:8.0.39
    environment:
      MYSQL_DB: ${MYSQL_DB:-db_shy}
      MYSQL_USER: ${MYSQL_USER:-root}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-supersaiyan}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-supersaiyan}
    healthcheck:
      test: ["CMD", "mysql_isready", "-d", "${MYSQL_DB:-db_shy}", "-U", "${MYSQL_USER:-root}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql/data:rw
    networks:
      - app-network

  mailer:
    image: axllent/mailpit
    ports:
      - "1025:1025"
      - "8025:8025"
    

networks:
  app-network:
    driver: bridge

volumes:
  database_data: