services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    networks:
      - app-network
    ports:
      - "8000:8000"  # Mapper le port 8000 du conteneur au port 8000 de l'hôte

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: supersaiyan
      MYSQL_DATABASE: db_shy
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data: